wallpaper {
    monitor = DP-1
    path = ~/.local/state/current-wallpaper
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = $WALLPAPERS_DIR/others_screen.jpg
    fit_mode = cover
}
