# config_directory/config.toml
[config]

[config.wallpaper]
# Whether to set the wallpaper or not
set = true

# The base command to run for applying the wallpaper.
# Keywords like {{ image }} or anything that works inside of hooks works here.
# You could also set a static color if you use the color keywords and the wallpaper setter supports it.
# Hard coded for main screen
# TODO script that generate a theme with matugen and then update selected screen with hyprpaper
command = "hyprctl hyprpaper wallpaper 'DP-1,{{image}},'"


[templates.waybar]
input_path = 'colors.css'
output_path = '/tmp/desktop-config/colors.css'
post_hook = "pkill -SIGUSR2 waybar"